// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAbkIaYTsPBWU5SE8PPFf-m2WisShr3XI',
    appId: '1:1096166031293:web:e1771c545d12a7537c5cd4',
    messagingSenderId: '1096166031293',
    projectId: 'todo-notes-8288f',
    authDomain: 'todo-notes-8288f.firebaseapp.com',
    storageBucket: 'todo-notes-8288f.firebasestorage.app',
    measurementId: 'G-Q8BQ0L2LE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhAHb9BopAZ-IB1my3z-9D10ihyViirU',
    appId: '1:1096166031293:android:3a731b014f74a8ec7c5cd4',
    messagingSenderId: '1096166031293',
    projectId: 'todo-notes-8288f',
    storageBucket: 'todo-notes-8288f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTu3psUr9aeHb8MIEP27tA5P3JrC6qNpE',
    appId: '1:1096166031293:ios:b9f2e553a36dfb4f7c5cd4',
    messagingSenderId: '1096166031293',
    projectId: 'todo-notes-8288f',
    storageBucket: 'todo-notes-8288f.firebasestorage.app',
    iosBundleId: 'com.example.toDoNotesApp',
  );
}
